### ISSUE TITLE
Add teams.

### ISSUE THREAD

**Issue by wildeyes** [DataHackIL/ninjathon#24]
## Description
When competition participant enter our system we want them to be able to find a team and create teams for their counterparts. We will also use this in order to track existing teams, set primary members(who's in charge) and enforce team size requirements.

## Requirements
- Create, update and delete teams.
- Add team members.
- Set team point of contact.
- Broadcast team is looking for members.
- Search teams who are looking for members.
- Contact teams.
- Should be able to add project description.
- Should be able to set competitions.

## Open Questions
1. If there are multiple events how should we differentiate between challenges, teams, etc?
2. Can you see teams that are not looking for a participant?

## Implementation
- Create a screen that lets the user to either create or join a team. (user comes here if he doesn't have a team)
- Create add team screen.
   - Can enter team details and create the team.
   - Redirects to the team management screen afterwards.
- Create team management screen.
  - Can add and remove team members.
  - Can update team details. (description, set a team member as post of contact, whether the team is looking for participants)
  - Can set competitions for the team.
  - Can delete the team.
- Create a screen that lets the user search "open" teams and see the point of contact member's email.

## Tasks Breakdown (per responsibility)
- [X] Create database models
- [X] Create app boilerplate
- [ ] Create add team screen
- [ ] Create show team profile screen.
- [ ] Add ability to manage team details and delete team
- [ ] Add ability to set competitions for the team
- [ ] Add ability to add / remove team members
- [ ] Create search teams screend

**Comment by wildeyes** [comment]
@adamr2 and I propose the following decision designs in regards to the team feature:

### relational db design
```
Team {
  id: String
  name: String
  description: String
}
Team_Challenges {
    id: String
    teamId: String // FK
    challengeId: String // FK
}
Team_Members {
    id: String
    teamId: String // FK
    userId: String // FK
}
Challenge {
    id: String
    description: String
    createdByUserId: String // FK, Defines whether it's a team project (created by a user of the project) or sponsered challenge (created by a "user" of the sponser)
}
```

### Screens
 - Team Profile
    - View the Profile (photo, description, which challenges taken, team members)
    - If part of the team: one can edit the profile details
        - Edit team description, pick a photo for the team
        - one can choose which challenges (via checkboxes) the team takes
        - ..Or/And create a team project (which will be represented by a challenge with a createdByUserId from the team)
        - Invite and delete team members by email (user gets an invitation/notification by email)
    - Share button for the team page on social media

Suggestions:
 - If the team won some prize, show it on their profile for fame

@shakedlokits please review

**Comment by wildeyes** [comment]
I'm continuing with this.

**Comment by wildeyes** [comment]
relevant PR: #32

**Comment by shakedlokits** [comment]
1. I do not understand the need for separate model for the challenges, because we would usually have only a small number of challenges?
2. What is team challenge in comparison to challenge?
3. I like the share button (: it's a good idea.
4. Should also add whether the team is open or not.
Could take a look at the [current model](https://github.com/DataHackIL/datahack_registration/blob/master/app/models/team.server.model.js)

**Comment by wildeyes** [comment]
```
	lookingText: {type :String, default: ""},
	isClosed: {type :Boolean, default: false},

```
is interesting

**Comment by wildeyes** [comment]
I'm starting `Create add team screen`, based on #32.
